import { useEffect, useRef, useState } from 'react';
import { api, ApiError, errorMessage } from './api';
import { CaptureController, SpeechController } from './audio';
import type { CaptureStatus, SpeechSnapshot, SpeechStatus } from './audio';
import Conversation, { Evaluation, Subtitles, timecode } from './Conversation';
import ReferencePanel from './ReferencePanel';
import type { ReferenceSelection } from './ReferencePanel';
import { isActive } from './session-state';
import { useSessionEvents } from './useSessionEvents';
import type { AppConfig, SessionCommand, SessionSettings, SessionSnapshot } from './types';

interface Preferences { original: boolean; subtitles: boolean; size: 'regular' | 'large' | 'largest'; position: 'top' | 'bottom' }
const preferenceDefaults: Preferences = { original: false, subtitles: true, size: 'large', position: 'top' };
const preferenceKey = 'speech-voice-presentation-v1';
function sessionFromUrl() {
  const value = new URL(location.href).searchParams.get('session');
  return value && /^[a-f0-9-]{32,36}$/i.test(value) ? value : null;
}
function updateSessionUrl(id: string | null) {
  const url = new URL(location.href);
  if (id) url.searchParams.set('session', id); else url.searchParams.delete('session');
  history.replaceState(null, '', `${url.pathname}${url.search}${url.hash}`);
}
function loadPreferences(): Preferences {
  try {
    const saved = JSON.parse(localStorage.getItem(preferenceKey) || '{}');
    return {
      original: typeof saved.original === 'boolean' ? saved.original : false,
      subtitles: typeof saved.subtitles === 'boolean' ? saved.subtitles : true,
      size: ['regular', 'large', 'largest'].includes(saved.size) ? saved.size : 'large',
      position: saved.position === 'bottom' ? 'bottom' : 'top',
    };
  } catch { return preferenceDefaults; }
}
const initialSpeech: SpeechStatus = { phase: 'idle', message: 'Text subtitles only', enabled: false, paused: false, blocked: false, countdownSeconds: null, model: null, voices: {} };
const initialCapture: CaptureStatus = { phase: 'idle', message: '', sampleRate: null };

function Brand() {
  return <a className="brand" href="#main" aria-label="Speech Voice, main workspace"><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" aria-hidden="true"><path d="M4 13v6M10 8v16M16 4v24M22 10v12M28 14v4" /></svg><strong>speech</strong><span>/ voice</span></a>;
}
function ModelReadiness({ config }: { config: AppConfig | null }) {
  if (!config) return <p className="hint">Connecting to the local server…</p>;
  const labels: Record<string, string> = { breeze: 'Breeze ASR', tencent: 'Tencent translation', nemotron: 'Nemotron speakers', openai: 'OpenAI services' };
  return <ul className="readiness-list">{Object.entries(config.models).map(([key, value]) => {
    const details = value && typeof value === 'object' && !Array.isArray(value) ? value : {};
    return <li key={key}><div><strong>{labels[key] || key}</strong><span>{typeof details.location === 'string' ? details.location : 'This computer'}</span></div><span className={details.available === false ? 'needs-setup' : ''}>{details.available === false ? 'Setup needed' : key === 'openai' ? 'Key configured' : 'Files detected'}</span></li>;
  })}</ul>;
}
function modelDisclosure(model: string, speech: boolean): string {
  const voice = speech ? ' Spoken English is generated by OpenAI.' : '';
  if (model === 'gpt-realtime-translate') return `Audio is sent to OpenAI for English and source captions. This mode does not use Astra, Tencent, terminology, or speaker detection.${voice}`;
  if (model === 'Breeze + OpenAI') return `Breeze recognizes speech on this computer. Transcript text and terminology are sent to OpenAI for translation and corrections; Tencent and speaker detection run locally.${voice}`;
  return `Audio is sent to OpenAI for transcription. Transcript text and terminology are sent to OpenAI for English translation and corrections. Tencent and speaker detection run locally.${voice}`;
}
export default function App() {
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [settings, setSettings] = useState<SessionSettings | null>(null);
  const [modelChoices, setModelChoices] = useState<Partial<Record<'microphone' | 'upload', string>>>({});
  const [session, setSession] = useState<SessionSnapshot | null>(null);
  const [tab, setTab] = useState<'microphone' | 'upload' | 'evaluation'>('microphone');
  const [preferences, setPreferences] = useState(loadPreferences);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);
  const [commandPending, setCommandPending] = useState(false);
  const commandGeneration = useRef(0);
  const currentSessionId = useRef(session?.id);
  currentSessionId.current = session?.id;
  const [devices, setDevices] = useState<MediaDeviceInfo[]>([]);
  const [deviceId, setDeviceId] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [inputGeneration, setInputGeneration] = useState(0);
  const replacement = useRef<{ previous: SessionSnapshot; nextId: string } | null>(null);
  const restoringId = useRef(sessionFromUrl());
  const [fileUrl, setFileUrl] = useState('');
  const [reference, setReference] = useState<ReferenceSelection>({ file: null, options: { format: 'auto' }, ready: false });
  const [speechState, setSpeechState] = useState<SpeechStatus>(initialSpeech);
  const [captureState, setCaptureState] = useState<CaptureStatus>(initialCapture);
  const capture = useRef<CaptureController | null>(null);
  const speech = useRef<SpeechController | null>(null);
  const acknowledgeRef = useRef<(value: unknown) => void>(() => {});
  const { connection, acknowledge } = useSessionEvents(session?.id, setSession, value => speech.current?.update(value as SpeechSnapshot));
  acknowledgeRef.current = acknowledge;
  const active = isActive(session);
  const frozen = active || working;
  const inputModel = tab === 'evaluation' ? 'Breeze + OpenAI' : modelChoices[tab] || settings?.model_pair;
  const selected = session && active ? session.settings : settings ? { ...settings, model_pair: inputModel! } : null;
  const exportFormats = session?.settings.model_pair === 'gpt-realtime-translate' ? ['txt', 'json'] : ['txt', 'json', 'csv', 'srt', 'vtt'];
  const inputStopped = session?.kind === 'microphone' ? session.input_finished : !!session?.stop_requested;
  const realtime = selected?.model_pair === 'gpt-realtime-translate';
  const speaking = session ? session.settings.speech_enabled : !!settings?.speech_enabled;
  const canCapture = typeof navigator !== 'undefined' && !!navigator.mediaDevices?.getUserMedia && !!window.AudioWorkletNode;

  useEffect(() => {
    const createCapture = () => new CaptureController({ onStatus: setCaptureState, onError: setError });
    capture.current = createCapture();
    speech.current = new SpeechController({ onStatus: setSpeechState, onAcknowledgement: value => acknowledgeRef.current({ type: 'speech.ack', ...value }) });
    return () => { capture.current?.dispose(); speech.current?.dispose(); capture.current = null; speech.current = null; };
  }, []);
  useEffect(() => {
    let cancelled = false;
    const recover = async () => {
      try {
        const value = await api.config();
        if (cancelled) return;
        setConfig(value); setSettings(value.defaults);
        setModelChoices({ microphone: value.defaults.model_pair, upload: value.defaults.model_pair });
        const id = restoringId.current;
        if (id) {
          try {
            const restored = await api.get(id);
            if (cancelled) return;
            restoringId.current = null;
            setSession(restored); setSettings(restored.settings); setTab(restored.kind);
            if (restored.kind !== 'evaluation') setModelChoices(current => ({ ...current, [restored.kind]: restored.settings.model_pair }));
            setNotice(restored.kind === 'microphone' && !restored.finished
              ? 'Your previous results are restored. Microphone capture was interrupted by the page reload; accepted audio will finish. Start a new conversation to record again.'
              : 'Your previous session is restored. Processing and available results are preserved.');
          } catch (failure) {
            if (cancelled) return;
            if (failure instanceof ApiError && failure.status === 404) { restoringId.current = null; updateSessionUrl(null); setNotice('The previous session expired or was cleared. Start a new conversation.'); }
            else setError(errorMessage(failure));
          }
        }
      } catch (failure) { if (!cancelled) setError(errorMessage(failure)); }
      finally { if (!cancelled) setLoading(false); }
    };
    void recover();
    return () => { cancelled = true; };
  }, []);
  useEffect(() => { if (!loading && (session || !restoringId.current)) updateSessionUrl(session?.id || null); }, [session?.id, loading]);
  useEffect(() => { commandGeneration.current += 1; setCommandPending(false); }, [session?.id]);
  useEffect(() => { try { localStorage.setItem(preferenceKey, JSON.stringify(preferences)); } catch { /* Preferences remain usable with browser storage blocked. */ } }, [preferences]);
  useEffect(() => {
    if (!file) { setFileUrl(''); return; }
    const url = URL.createObjectURL(file); setFileUrl(url);
    return () => URL.revokeObjectURL(url);
  }, [file]);
  useEffect(() => {
    let alive = true;
    const refresh = () => navigator.mediaDevices?.enumerateDevices?.().then(value => { if (alive) setDevices(value.filter(item => item.kind === 'audioinput')); }).catch(() => {});
    void refresh(); navigator.mediaDevices?.addEventListener?.('devicechange', refresh);
    return () => { alive = false; navigator.mediaDevices?.removeEventListener?.('devicechange', refresh); };
  }, []);
  useEffect(() => {
    const pending = replacement.current;
    if (!pending || session?.id !== pending.nextId) return;
    if (session.status === 'failed') {
      replacement.current = null; setSession(pending.previous);
      setError(session.error || 'The new session could not start. Your previous results are preserved.');
      void api.remove(pending.nextId).catch(() => {});
    } else if (session.status !== 'preparing' && (session.kind !== 'microphone' || captureState.phase === 'recording')) {
      replacement.current = null; void api.remove(pending.previous.id).catch(() => {});
    }
  }, [session, captureState.phase]);
  function setting<K extends keyof SessionSettings>(key: K, value: SessionSettings[K]) { setSettings(current => current ? { ...current, [key]: value } : current); }
  function preference<K extends keyof Preferences>(key: K, value: Preferences[K]) { setPreferences(current => ({ ...current, [key]: value })); }
  async function retryConfig() {
    setLoading(true); setError('');
    try { const value = await api.config(); setConfig(value); setSettings(value.defaults); setModelChoices({ microphone: value.defaults.model_pair, upload: value.defaults.model_pair }); }
    catch (failure) { setError(errorMessage(failure)); }
    finally { setLoading(false); }
  }
  async function command(value: SessionCommand) {
    if (!session) return;
    const id = session.id;
    const request = ++commandGeneration.current;
    const isCurrent = () => currentSessionId.current === id && commandGeneration.current === request;
    setCommandPending(true); setError('');
    try {
      const next = await api.command(id, value);
      if (!isCurrent()) return;
      setSession(current => current?.id === id && next?.revision >= current.revision ? next : current);
      if (value.type === 'terminology') setNotice('Terminology reloaded for this session.');
    } catch (failure) { if (isCurrent()) setError(errorMessage(failure)); }
    finally { if (isCurrent()) setCommandPending(false); }
  }
  async function start() {
    if (!settings || working || active) return;
    if (tab !== 'microphone' && !file) { setError('Choose a WAV file first.'); return; }
    if (tab === 'evaluation' && (!reference.file || !reference.ready)) { setError('Preview the reference and choose a source column before evaluating.'); return; }
    if (settings.speech_enabled) void speech.current?.unlock();
    setWorking(true); setError(''); setNotice('');
    const previous = session;
    let next: SessionSnapshot | undefined;
    try {
      const requested = { ...settings, model_pair: inputModel!, ...(tab !== 'microphone' ? { translation_type: 'Compare all translations' } : {}), ...(tab === 'evaluation' ? { speech_enabled: false } : {}) };
      next = tab === 'microphone' ? await api.create(requested) : await api.upload(file!, requested, tab === 'evaluation' ? reference.file! : undefined, reference.options);
      restoringId.current = null;
      if (previous) replacement.current = { previous, nextId: next.id };
      setSession(next);
      if (tab === 'microphone') {
        await capture.current?.start({ sessionId: next.id, deviceId: deviceId || undefined });
        const inputs = await navigator.mediaDevices.enumerateDevices();
        setDevices(inputs.filter(item => item.kind === 'audioinput'));
      }
    } catch (failure) {
      setError(errorMessage(failure));
      if (next) {
        if (previous && replacement.current?.nextId === next.id) {
          replacement.current = null; setSession(previous); void api.remove(next.id).catch(() => {});
        } else {
          try { const stopped = await api.command(next.id, { type: 'stop' }); setSession(current => current?.id === next!.id ? stopped : current); } catch { /* Retain the recoverable session and original failure. */ }
        }
      }
    } finally { setWorking(false); }
  }
  async function stop() {
    if (!session) return;
    setWorking(true); setError('');
    try {
      if (session.kind === 'microphone') await capture.current?.stop();
      const next = await api.command(session.id, { type: 'stop' });
      setSession(current => current?.id === next.id && next.revision >= current.revision ? next : current);
      setNotice('Input stopped. Accepted audio and translations will finish; your results remain available.');
    } catch (failure) { setError(errorMessage(failure)); }
    finally { setWorking(false); }
  }
  async function clear() {
    if (!session) return;
    setWorking(true); setError('');
    capture.current?.dispose(); capture.current = new CaptureController({ onStatus: setCaptureState, onError: setError });
    speech.current?.stop();
    try {
      await api.remove(session.id);
      const previous = replacement.current?.previous; replacement.current = null;
      if (previous) await api.remove(previous.id);
      restoringId.current = null;
      setSession(null); setCaptureState(initialCapture); setFile(null);
      setReference({ file: null, options: { format: 'auto' }, ready: false }); setInputGeneration(current => current + 1);
      setNotice('Session ended and cleared from the server.');
    } catch (failure) { setError(errorMessage(failure)); }
    finally { setWorking(false); }
  }
  function toggleSpeech(enabled: boolean) {
    if (enabled) { speech.current?.update(null); void speech.current?.unlock(); } else speech.current?.stop();
    setting('speech_enabled', enabled);
    if (session) void command({ type: 'speech', enabled, model: settings?.speech_model, mode: settings?.astra_speech_mode, speaker_voices: settings?.speaker_voices });
  }
  function toggleCorrections(enabled: boolean) {
    setting('corrections_enabled', enabled);
    if (session && session.providers.includes('astra')) void command({ type: 'corrections', enabled });
  }
  const progress = session?.progress;
  const providerErrors = !!session?.segments.some(segment => Object.values(segment.translations).some(value =>
    !!value.error || ['failed', 'unavailable', 'error'].includes(value.status)));
  const status = session ? session.status === 'complete' && providerErrors ? 'Completed with errors' : session.status === 'recording' ? 'Live' : session.status.charAt(0).toUpperCase() + session.status.slice(1) : loading ? 'Connecting' : config ? 'Ready to start' : 'Server unavailable';
  const disclosure = session?.processing_disclosure || (settings ? modelDisclosure(inputModel!, settings.speech_enabled) : 'This app runs on your computer and uses OpenAI services.');
  const subtitles = <Subtitles session={session} original={preferences.original} visible={preferences.subtitles} size={preferences.size} />;

  return <>
    <a className="skip-link" href="#main">Skip to workspace</a>
    <header className="site-header"><Brand /><div className="header-right"><span className="server-pill"><i className={config && connection !== 'disconnected' ? 'green-dot' : 'amber-dot'} />{connection === 'disconnected' ? 'Reconnecting to server' : 'Local workspace'}</span><span className="header-language">English output <span>EN</span></span></div></header>
    <main id="main" className="page">
      <div className="page-heading"><div><p className="eyebrow">Listen together. Follow every word.</p><h1>Live English, for every conversation.</h1><p className="page-intro">Real-time subtitles, thoughtful corrections, and a voice when you need one.</p></div><span className="workspace-tag">Mandarin / Chinglish <span>→ English</span></span></div>
      {error && <div className="notice error" role="alert"><span>{error}</span><button className="icon-button" onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}
      {notice && <div className="notice success" role="status"><span>{notice}</span><button className="icon-button" onClick={() => setNotice('')} aria-label="Dismiss notice">×</button></div>}
      {connection === 'disconnected' && <div className="notice error" role="alert">The connection to the server was lost. Reconnecting to your existing results; microphone input is not restarted automatically.</div>}
      {!config && !loading && <button className="button primary" onClick={() => void retryConfig()}>Reconnect to server</button>}
      <div className="workspace-grid">
        <aside className="controls-card" aria-label="Session controls">
          <div className="card-heading"><span className="eyebrow">Your input</span><span className="pill">中文 + EN</span></div>
          <div className="input-tabs" role="tablist" aria-label="Audio source">{([['microphone', 'Microphone'], ['upload', 'Upload WAV'], ['evaluation', 'Evaluate']] as const).map(([value, label]) => <button role="tab" aria-selected={tab === value} aria-controls="input-panel" id={`tab-${value}`} key={value} disabled={frozen} onClick={() => { if (tab === 'evaluation' && value !== tab) setReference({ file: null, options: { format: 'auto' }, ready: false }); setTab(value); }}>{label}</button>)}</div>
          <div id="input-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
            {tab === 'microphone' ? <><label className="field">Microphone<select disabled={frozen || !canCapture} value={deviceId} onChange={event => setDeviceId(event.target.value)}><option value="">System default</option>{devices.filter(item => item.deviceId !== 'default').map((device, index) => <option key={device.deviceId} value={device.deviceId}>{device.label || `Microphone ${index + 1}`}</option>)}</select></label>{!canCapture && <p className="notice small">Microphone capture requires a browser with AudioWorklet support on localhost or HTTPS. You can still upload a WAV file.</p>}</> : <>
              <label className="field upload-field">WAV recording<input key={inputGeneration} type="file" accept=".wav,audio/wav,audio/x-wav" disabled={frozen} onChange={event => setFile(event.target.files?.[0] || null)} /></label>
              {file && <p className="file-description">{file.name} · {(file.size / 1048576).toFixed(1)} MiB</p>}
              {fileUrl && <audio controls preload="metadata" src={fileUrl} aria-label="Preview uploaded recording" />}
              {tab === 'evaluation' && <><p className="hint">Evaluation uses the local Breeze baseline. References are for comparison only.</p><ReferencePanel key={inputGeneration} disabled={frozen} onChange={setReference} /></>}
            </>}
          </div>
          <div className="start-actions">
            {active ? <button className="button primary full" disabled={working || inputStopped} onClick={() => void stop()}><span className="stop-symbol" />{working ? 'Stopping…' : inputStopped ? 'Finishing translations…' : tab === 'microphone' ? 'Stop recording' : 'Stop file translation'}</button> : <button className="button primary full" disabled={!config || loading || working || (tab === 'microphone' && !canCapture) || (tab !== 'microphone' && !file) || (tab === 'evaluation' && !reference.ready)} onClick={() => void start()}><span className="play-symbol" />{working ? 'Starting…' : tab === 'microphone' ? session ? 'Start new conversation' : 'Start subtitles' : tab === 'evaluation' ? 'Evaluate recording' : 'Translate recording'}</button>}
            <p className="hint action-hint">{tab === 'microphone' ? 'Allow microphone access when your browser asks.' : 'Preview your audio, then start translation.'}{session && !active ? ' Starting again replaces these results.' : ''}</p>
          </div>
          <div className="speech-controls"><label className="switch-field"><span><strong>Spoken English</strong><small>Listen to the translation</small></span><input type="checkbox" role="switch" checked={speaking} disabled={!settings || commandPending || tab === 'evaluation'} onChange={event => toggleSpeech(event.target.checked)} /></label>
            <details className="voice-settings"><summary>Voice settings</summary><div className="speech-options"><label className="field">Text-to-speech model<select value={settings?.speech_model || ''} disabled={speaking && !!session} onChange={event => setting('speech_model', event.target.value)}>{config?.speech_models.map(model => <option key={model}>{model}</option>)}</select></label>
              {!realtime && <><label className="field">Speech review<select value={settings?.astra_speech_mode || ''} disabled={speaking && !!session} onChange={event => setting('astra_speech_mode', event.target.value)}>{config?.speech_modes.map(mode => <option key={mode}>{mode}</option>)}</select></label><label className="inline-check"><input type="checkbox" checked={!!settings?.speaker_voices} disabled={speaking && !!session} onChange={event => setting('speaker_voices', event.target.checked)} /> Different voice per speaker</label></>}
              <p className="hint">AI-generated voice. Starts 60 seconds after the first eligible English translation. Enabling during a session speaks new segments only. Use headphones while recording.</p>
            </div></details>
          </div>
          <details className="settings-details"><summary>Models & translation settings</summary>
            {settings && <div className="settings-content">
              <label className="field">Transcription + translation model<select value={inputModel || ''} disabled={frozen || tab === 'evaluation'} onChange={event => { if (tab !== 'evaluation') setModelChoices(current => ({ ...current, [tab]: event.target.value })); }}>{config?.model_pairs.map(model => <option key={model}>{model}</option>)}</select></label>
              <label className="field">Translation type<select value={tab === 'microphone' ? settings.translation_type : 'Compare all translations'} disabled={frozen || realtime || tab !== 'microphone'} onChange={event => setting('translation_type', event.target.value)}>{config?.translation_types.map(type => <option key={type}>{type}</option>)}</select></label>
              <label className="inline-check"><input type="checkbox" checked={session && active ? session.settings.corrections_enabled : settings.corrections_enabled} disabled={realtime || commandPending} onChange={event => toggleCorrections(event.target.checked)} /> Astra corrections</label>
              <label className="inline-check"><input type="checkbox" checked={settings.diarization} disabled={frozen || realtime} onChange={event => setting('diarization', event.target.checked)} /> Nemotron speaker detection</label>
              <p className="hint">Speaker detection runs locally. Model and speaker settings stay fixed for the current conversation.</p>
              <label className="field">Correction model<input value={settings.correction_model} disabled={frozen || realtime} onChange={event => setting('correction_model', event.target.value)} /></label>
              <label className="field">Reasoning effort<select value={settings.reasoning_effort} disabled={frozen || realtime} onChange={event => setting('reasoning_effort', event.target.value)}>{['none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'].map(effort => <option key={effort}>{effort}</option>)}</select></label>
              <label className="field">Reasoning + output token cap<input type="number" min="512" max="16384" step="512" value={settings.max_output_tokens} disabled={frozen || realtime} onChange={event => setting('max_output_tokens', Number(event.target.value))} /></label>
              <label className="field">Correction confidence <output>{settings.confidence_threshold.toFixed(2)}</output><input type="range" min="0" max="1" step="0.05" value={settings.confidence_threshold} disabled={frozen || realtime} onChange={event => setting('confidence_threshold', Number(event.target.value))} /></label>
              <label className="field">Glossary file path<input placeholder="Optional local glossary" value={settings.glossary_path || ''} disabled={realtime} onChange={event => setting('glossary_path', event.target.value)} /></label>
              <label className="field">Do-not-translate file path<input placeholder="Optional local word list" value={settings.dnt_path || ''} disabled={realtime} onChange={event => setting('dnt_path', event.target.value)} /></label>
              <p className="hint">CSV, TSV, JSON or XLSX glossary; TXT also works for do-not-translate lists. References never become terminology.</p>
              {session && <button className="button secondary full small" disabled={commandPending || realtime} onClick={() => void command({ type: 'terminology', glossary_path: settings.glossary_path, dnt_path: settings.dnt_path })}>Reload terminology</button>}
            </div>}
          </details>
          <details className="settings-details"><summary>Service & model readiness</summary><p className="hint">Local models load on first use. Preparation can take longer than subsequent sessions.</p><ModelReadiness config={config} /></details>
          <div className="privacy-note"><span className="eyebrow">Processing & privacy</span><p>{disclosure}</p><p>Results stay in server memory until you clear them. Disconnected sessions expire after 30 minutes. Audio is released after processing. Export saves a copy on your device.</p></div>
        </aside>
        <div className="conversation-workspace">
          <section className="session-toolbar" aria-label="Session status"><div className="session-heading"><span className={`live-indicator ${active ? 'active' : ''}`} /><div><strong>{status}</strong><span>{session?.name || 'Your conversation, translated as it happens'}</span></div></div><div className="session-actions">{session && <><details className="export-menu"><summary className="button small secondary">Export <span aria-hidden="true">↓</span></summary><div>{exportFormats.map(format => <a key={format} href={`/api/sessions/${encodeURIComponent(session.id)}/exports/${format}`} download>{format.toUpperCase()}</a>)}</div></details><button className="button small ghost" disabled={working} onClick={() => void clear()}>End and clear</button></>}</div></section>
          {active && <div className="processing-status" role="status"><div><span>{captureState.phase === 'recording' ? 'Microphone is live' : session?.status === 'preparing' ? 'Preparing audio and models…' : 'Processing your conversation…'}</span>{progress && <span>{progress.total ? `${progress.completed} / ${progress.total} segments` : `${timecode(progress.received_seconds)} received`}</span>}</div>{progress && progress.total > 0 && <progress max={progress.total} value={progress.completed} aria-label="Transcription progress" />}{session?.diarization && typeof session.diarization.status === 'string' && <span className="hint">Nemotron · {session.diarization.status.replaceAll('_', ' ')}{typeof session.diarization.processed_seconds === 'number' ? ` · ${timecode(session.diarization.processed_seconds)} processed` : ''}</span>}</div>}
          {session?.error && <div className="notice error" role="alert">{session.error}</div>}
          {speaking && <section className="speech-player" aria-label="English speech player"><div><span className="voice-icon" aria-hidden="true">≋</span><div><strong>{speechState.countdownSeconds != null ? `English voice begins in ${speechState.countdownSeconds}s` : speechState.message || 'Preparing English voice'}</strong><span>{settings?.speech_model} · AI-generated English</span></div></div><div>{speechState.blocked && <button className="button small secondary" onClick={() => void speech.current?.unlock()}>Enable sound</button>}{!speechState.blocked && <button className="button small secondary" onClick={() => speechState.paused ? speech.current?.resume() : speech.current?.pause()}>{speechState.paused ? 'Resume voice' : 'Pause voice'}</button>}<button className="button small ghost" disabled={commandPending} onClick={() => toggleSpeech(false)}>Stop voice</button></div></section>}
          <div className="subtitle-controls"><label className="inline-check"><input type="checkbox" checked={preferences.original} onChange={event => preference('original', event.target.checked)} /> Show original</label><div><label className="compact-select">Text size<select value={preferences.size} onChange={event => preference('size', event.target.value as Preferences['size'])}><option value="regular">Regular</option><option value="large">Large</option><option value="largest">Extra large</option></select></label><label className="compact-select">Position<select value={preferences.position} onChange={event => preference('position', event.target.value as Preferences['position'])}><option value="top">Top</option><option value="bottom">Bottom</option></select></label><button className="button small ghost" onClick={() => preference('subtitles', !preferences.subtitles)}>{preferences.subtitles ? 'Hide subtitles' : 'Show subtitles'}</button></div></div>
          {preferences.position === 'top' && subtitles}
          {session?.evaluation && <Evaluation evaluation={session.evaluation} />}
          <Conversation session={session} original={preferences.original} onRetry={provider => void command({ type: 'retry', provider })} commandPending={commandPending} />
          {preferences.position === 'bottom' && subtitles}
          <footer className="workspace-footer"><span>English-only output · Anonymous speaker labels</span><a href="/guide/diarization" target="_blank" rel="noreferrer">How speaker detection works <span aria-hidden="true">↗</span></a></footer>
        </div>
      </div>
    </main>
  </>;
}
